name = "ProcessModels"
uuid = "3852ba64-8153-459f-9b4c-35a924b2b981"
authors = ["Jonathan Mädler <j.maedler@gmx.net>"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
